### ISSUE TITLE
Reported price did not double on daily auction start

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome#28]
After daily auction ended with 0 MET available and price at the lower limit of 0.0000033 ETH, the next auction started with 2880 MET but `currentPrice` remained at 0.0000033 ETH.

Then, when a buy tx was sent 63' after the auction started, the effective purchase price was 0.000003503976584 ETH, `currentPrice` started to show the correct price and stated to descend every minute.

Buy txid: 0x9c7c8312ecd033e564f53c37cde63f6633f6bbe095aceb65f2492c07ce6b6e57

Contracts commit: 5fd9233
Auctions: 0x9aeb1035b327f4f81198090f4183f21ca6fcb040

**Comment by filcap** [comment]
Assigned to @patidarmanoj10

**Comment by patidarmanoj10** [comment]
I am working on this.

**Comment by patidarmanoj10** [comment]
@rokso  please add your comment about this fix and send PR.

**Comment by rokso** [comment]
@patidarmanoj10 I have fixed this issue and PR is submitted, please review.

**Comment by patidarmanoj10** [comment]
CurrentPrice function was not returning correct value. This is fixed now. Below is expected behaviour
1) If auction sold out and current tick is within same auction then currentPrice() will return last purchase price
2) if auction sold out and current tick is next auction then currentPrice() will return 2x of last purchase price.
3) if auction sold out and 1 or more auctions missed then currentPrice() will be lastPurcahsePrice/100 +1
4) if auction timedout and currentTick is in next auction then currentPrice() will be 0.99 descended price every minute from start of auction. Start Price of this auction will be 2x of price at last tick of previous auction or 2x of floor price whichever is higher.

Currently floor price in initial auction and daily auction is 0.0000033 .  One discussion going on issue #25 whether daily auction price should be have 0.0000033  eth/met or 1 wei floor price.  This is waiting for confirmation.

**Comment by twleung** [comment]
Issue 25 resolved, so this is all done now.
