### ISSUE TITLE
Accumulated subscription balance can be manipulated by subscriber

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome#32]
Severity: High
Audit Report: Zeppelin Page 9

**Comment by patidarmanoj10** [comment]
WONT FIX.    I think allowing override/cancellation  is  justified because withdraw of  weekly subscription payment is responsibility of beneficiary.  If beneficiary not withdrawing weekly then he run into risk . Same risk also exist when owner has no balance in his account and due amount accumulated.
